application: lizardanalyzer
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /.*
  script: website.application

libraries:
- name: webapp2
  version: latest
