#!/usr/bin/env python
from lizard import lizard_main
import languages
import sys

lans = [languages.JavaReader,
    languages.JavaScriptReader,
    languages.PythonReader,
    languages.ObjCReader,
    languages.TTCNReader,
    languages.SwiftReader]

if __name__ == "__main__":
    lizard_main(sys.argv, lans)
